<!DOCTYPE html>
<head>
    <meta charset="utf-8">
</head>
<body>

    <form class="form-horizontal">
    <fieldset>

    <!-- Form Name -->
    <legend>New User</legend>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="textinput">Name:</label>  
      <div class="col-md-4">
      <input id="name" type="text" placeholder="Name..." name="name" required autocomplete="off" class="form-control input-md">
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="textinput">Username:</label>  
      <div class="col-md-4">
      <input id="username" type="text" placeholder="Username..." name="username" required autocomplete="off" class="form-control input-md">
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="textinput">Date: </label>  
      <div class="col-md-4">
      <input id="Date" type="Date" placeholder="dd-mm-yyyy" name="dteBirth" required pattern="(0[1-9]|1[0-9]|2[0-9]|3[01]).(0[1-9]|1[012]).[0-9]{4}" class="form-control input-md">
      </div>
    </div>

                    <input type="hidden" name="profile" value="u">
                    <input type="hidden" name="active" value="y">

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="textinput">Email: </label>  
      <div class="col-md-4">
      <input id="email" type="email" id="email" placeholder="Email..." name="email" required autocomplete="off" pattern="[^ @]+@[^ @]+.[a-z]+" class="form-control input-md">
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="textinput">Password:</label>  
      <div class="col-md-4">
      <input id="password" type="text" placeholder="Password..." name="pwd" required autocomplete="off" class="form-control input-md">
      </div>
    </div>

    <!-- Button -->
    <br>
    <button class="btn btn-success botao" type="submit">Cadastrar!</button>

    </fieldset>
    </form>

</body>
</html>

