
<!DOCTYPE html>
<html>
  <head>
	<LINK rel="stylesheet" type="text/css" href="easyTrip.css">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACeINkvYJeWxeaSs7u4ZVJNfmQdCSvE6Q&callback=initMap"></script>
	<script type="text/javascript">

		if (navigator.geolocation) {
		    navigator.geolocation.getCurrentPosition(success, error);
		} else {
		    error('Seu navegador não suporta <b style="color:black;background-color:#ffff66">Geolocalização</b>!');
		}
		function success(position) {
		    var s = document.querySelector('#status');
		
		    if (s.className == 'success') {
		        return;
		    }
		
		    s.innerHTML = "Você foi localizado!";
		    s.className = 'success';
		
		    var mapcanvas = document.createElement('div');
		        mapcanvas.id = 'map';
		        mapcanvas.style.height = '400px';
		        mapcanvas.style.width = '560px';
		
		    document.querySelector('article').appendChild(mapcanvas);
		
		    var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
		
		    var myOptions = {
		        zoom: 10,
		        center: latlng,
		        mapTypeControl: false,
		        navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
		        mapTypeId: google.maps.MapTypeId.ROADMAP
		    };
		
		    var map = new google.maps.Map(document.getElementById("map"), myOptions);
		    var marker = new google.maps.Marker({
		        position: latlng,
		        map: map,
		        title:"Você está aqui!"
		    });
		
		}
		
		function error(msg) {
		    var s = document.querySelector('#status');
		        s.innerHTML = typeof msg == 'string' ? msg : "falhou";
		        s.className = 'fail';
		}

    </script>
  </head>
  <body>
  <div id="map">
	<section>
	    <article>
	        <p><span id="status">Por favor aguarde enquanto nós tentamos locar você...</span></p>
	    </article>
	 </section>
  </div>
  </body>
</html>