
<!DOCTYPE html>
<html>
  <head>
	<LINK rel="stylesheet" type="text/css" href="easyTrip.css">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACeINkvYJeWxeaSs7u4ZVJNfmQdCSvE6Q&callback=initMap"></script>
    <script type="text/javascript">

    

	 function initMap() {
		 var UserPosition = new google.maps.LatLng(-18.8800497, -47.05878999999999);
         var myOptions = {
             center: UserPosition,
             zoom: 4,
             mapTypeId: google.maps.MapTypeId.ROADMAP
         };
         var map = new google.maps.Map(document.getElementById("map"), myOptions);
         var geocoder = new google.maps.Geocoder();
         var infowindow = new google.maps.InfoWindow;
	 }
	 
	 if (navigator.geolocation) {
		    navigator.geolocation.getCurrentPosition(success, error);
		} else {
		    error('Seu navegador não suporta <b style="color:black;background-color:#ffff66">Geolocalização</b>!');
		}
		
	 function localizarUsuario(){
			
			function success(position) {
			    var status = document.querySelector('#status');
			
			    if (status.className == 'success') {
			        return;
			    }
			
			    status.innerHTML = "Você foi localizado!";
			    status.className = 'success';
			
			    var mapcanvas = document.createElement('div');
			        mapcanvas.id = 'map';
			
			    document.querySelector('article').appendChild(mapcanvas);
			
			    var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
			
			    var myOptions = {
			        zoom: 10,
			        center: latlng,
			        mapTypeControl: false,
			        navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
			        mapTypeId: google.maps.MapTypeId.ROADMAP
			    };
			
			    var map = new google.maps.Map(document.getElementById("map"), myOptions);
			    var marker = new google.maps.Marker({
			        position: latlng,
			        map: map,
			        title:"Você está aqui!"
			    });
			
			}
			
			function error(msg) {
			    var s = document.querySelector('#status');
			        s.innerHTML = typeof msg == 'string' ? msg : "falhou";
			        s.className = 'fail';
			}
		}

	 function showError(error){
	  switch(error.code)
	    {
	    case error.PERMISSION_DENIED:
	      x.innerHTML="Usuário rejeitou a solicitação de Geolocalização."
	      break;
	    case error.POSITION_UNAVAILABLE:
	      x.innerHTML="Localização indisponível."
	      break;
	    case error.TIMEOUT:
	      x.innerHTML="A requisição expirou."
	      break;
	    case error.UNKNOWN_ERROR:
	      x.innerHTML="Algum erro desconhecido aconteceu."
	      break;
	    }
	  }

    </script>
  </head>
  <body onload="initMap()">
      	<button id="btnLocal" onClick="localizarUsuario()">Minha Localiza&ccedil;&atilde;o</button> <br>
    	<div id="map"></div>
  </body>
</html>