-- MySQL Script generated by MySQL Workbench
-- 09/20/16 19:17:03
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EasyTripDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EasyTripDB` ;
CREATE SCHEMA IF NOT EXISTS `EasyTripDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `EasyTripDB` ;

-- -----------------------------------------------------
-- Table `EasyTripDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EasyTripDB`.`User` ;

CREATE TABLE IF NOT EXISTS `EasyTripDB`.`User` (
  `IdUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `DteBirth` DATE NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Profile` CHAR NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `PositionLat` INT NOT NULL,
  `PositionLgn` INT NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyTripDB`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EasyTripDB`.`Country` ;

CREATE TABLE IF NOT EXISTS `EasyTripDB`.`Country` (
  `IdCountry` INT NOT NULL AUTO_INCREMENT,
  `CountryName` VARCHAR(50) NOT NULL,
  `CountryIni` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IdCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyTripDB`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EasyTripDB`.`State` ;

CREATE TABLE IF NOT EXISTS `EasyTripDB`.`State` (
  `IidState` INT NOT NULL AUTO_INCREMENT,
  `StateName` VARCHAR(45) NOT NULL,
  `StateIni` VARCHAR(2) NOT NULL,
  `CodCountry` INT NOT NULL,
  PRIMARY KEY (`IidState`),
  INDEX `fk_State_Country1_idx` (`CodCountry` ASC),
  CONSTRAINT `fk_State_Country1`
    FOREIGN KEY (`CodCountry`)
    REFERENCES `EasyTripDB`.`Country` (`IdCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyTripDB`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EasyTripDB`.`City` ;

CREATE TABLE IF NOT EXISTS `EasyTripDB`.`City` (
  `IdCity` INT NOT NULL AUTO_INCREMENT,
  `CityName` VARCHAR(45) NOT NULL,
  `CityIni` VARCHAR(3) NOT NULL,
  `CodState` INT NOT NULL,
  PRIMARY KEY (`IdCity`),
  INDEX `fk_City_State1_idx` (`CodState` ASC),
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`CodState`)
    REFERENCES `EasyTripDB`.`State` (`IidState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyTripDB`.`Local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EasyTripDB`.`Local` ;

CREATE TABLE IF NOT EXISTS `EasyTripDB`.`Local` (
  `IdLocal` INT NOT NULL AUTO_INCREMENT,
  `LocalName` VARCHAR(80) NOT NULL,
  `Description` TEXT NULL,
  `CodCity` INT NOT NULL,
  PRIMARY KEY (`IdLocal`),
  INDEX `fk_Local_City1_idx` (`CodCity` ASC),
  CONSTRAINT `fk_Local_City1`
    FOREIGN KEY (`CodCity`)
    REFERENCES `EasyTripDB`.`City` (`IdCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyTripDB`.`Accomodation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EasyTripDB`.`Accomodation` ;

CREATE TABLE IF NOT EXISTS `EasyTripDB`.`Accomodation` (
  `idAccomodation` INT NOT NULL AUTO_INCREMENT,
  `AccName` VARCHAR(80) NOT NULL,
  `AccCNPJ` VARCHAR(45) NOT NULL,
  `AccAdress` VARCHAR(45) NOT NULL,
  `AccPhone` VARCHAR(10) NOT NULL,
  `CodLocal` INT NOT NULL,
  PRIMARY KEY (`idAccomodation`),
  INDEX `fk_Accomodation_Local1_idx` (`CodLocal` ASC),
  CONSTRAINT `fk_Accomodation_Local1`
    FOREIGN KEY (`CodLocal`)
    REFERENCES `EasyTripDB`.`Local` (`IdLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
